spring:
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:mysql://localhost:3306/scrumcloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: scrumcloud
    password: scrumcloud
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
  jpa:
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect